### ISSUE TITLE
Yarn build error

### ISSUE THREAD

**Issue by chetan8300** [datalayer/jupyter-react#13]
## Description

Yarn build gives typescript errors from @jupyterlab/completer, FileBrowserAdapter, NotebookAdapter, ConsoleAdapter. I have followed the same steps given in the Readme file and am still stuck on the build.

## Reproduce

Followed steps from Contribute section from Readme file

Is there any specific process to be followed other than the given steps to generate a build?

## Context

- Datalayer version: Latest from the Main branch
- Operating System and version: MacOS 12.3
- Browser and version: Microsoft Edge - Version 99.0.1150.46

<details><summary>Console Output</summary>
<pre>
yarn run v1.22.5
$ gulp resources-to-lib && tsc && webpack
[10:49:49] Using gulpfile ~/Projects/jupyter-react/gulpfile.js
[10:49:49] Starting 'resources-to-lib'...
[10:49:49] Finished 'resources-to-lib' after 10 ms
node_modules/@jupyterlab/completer/lib/widget.d.ts:56:9 - error TS2380: 'get' and 'set' accessor must have the same type.

56     set showDocsPanel(showDoc: boolean | null);
           ~~~~~~~~~~~~~

node_modules/@jupyterlab/completer/lib/widget.d.ts:57:9 - error TS2380: 'get' and 'set' accessor must have the same type.

57     get showDocsPanel(): boolean;
           ~~~~~~~~~~~~~

src/components/console/ConsoleAdapter.ts:37:9 - error TS2322: Type 'import("/Users/user1/Projects/jupyter-react/node_modules/@jupyterlab/services/lib/manager").ServiceManager.IManager' is not assignable to type 'import("/Users/user1/Projects/jupyter-react/node_modules/@jupyterlab/translation/node_modules/@jupyterlab/services/lib/manager").ServiceManager.IManager'.
  Types of property 'builder' are incompatible.
    Type 'import("/Users/user1/Projects/jupyter-react/node_modules/@jupyterlab/services/lib/builder/index").Builder.IManager' is not assignable to type 'import("/Users/user1/Projects/jupyter-react/node_modules/@jupyterlab/translation/node_modules/@jupyterlab/services/lib/builder/index").Builder.IManager'.

37         manager: serviceManager,
           ~~~~~~~

  node_modules/@jupyterlab/console/lib/panel.d.ts:75:9
    75         manager: ServiceManager.IManager;
               ~~~~~~~
    The expected type comes from property 'manager' which is declared here on type 'IOptions'

src/components/filebrowser/FileBrowserAdapter.ts:63:9 - error TS2322: Type 'import("/Users/user1/Projects/jupyter-react/node_modules/@jupyterlab/services/lib/manager").ServiceManager.IManager' is not assignable to type 'import("/Users/user1/Projects/jupyter-react/node_modules/@jupyterlab/translation/node_modules/@jupyterlab/services/lib/manager").ServiceManager.IManager'.

63         manager,
           ~~~~~~~

  node_modules/@jupyterlab/docmanager/lib/manager.d.ts:277:9
    277         manager: ServiceManager.IManager;
                ~~~~~~~
    The expected type comes from property 'manager' which is declared here on type 'IOptions'

src/components/notebook/NotebookAdapter.ts:129:7 - error TS2322: Type 'ServiceManager' is not assignable to type 'IManager'.
  Types of property 'builder' are incompatible.
    Type 'import("/Users/user1/Projects/jupyter-react/node_modules/@jupyterlab/services/lib/builder/index").Builder.IManager' is not assignable to type 'import("/Users/user1/Projects/jupyter-react/node_modules/@jupyterlab/translation/node_modules/@jupyterlab/services/lib/builder/index").Builder.IManager'.
      Types have separate declarations of a private property '_url'.

129       manager: this.serviceManager,
          ~~~~~~~

  node_modules/@jupyterlab/docregistry/lib/context.d.ts:254:9
    254         manager: ServiceManager.IManager;
                ~~~~~~~
    The expected type comes from property 'manager' which is declared here on type 'IOptions<INotebookModel>'

src/ipywidgets/IPyWidgetsJupyterLabPlugin.ts:83:43 - error TS2345: Argument of type 'import("/Users/user1/Projects/jupyter-react/node_modules/@jupyterlab/rendermime/lib/tokens").IRenderMimeRegistry' is not assignable to parameter of type 'import("/Users/user1/Projects/jupyter-react/node_modules/@jupyter-widgets/html-manager/node_modules/@jupyterlab/rendermime/lib/tokens").IRenderMimeRegistry'.
  The types returned by 'createModel(...)' are incompatible between these types.
    Type 'import("/Users/user1/Projects/jupyter-react/node_modules/@jupyterlab/rendermime/lib/mimemodel").MimeModel' is not assignable to type 'import("/Users/user1/Projects/jupyter-react/node_modules/@jupyter-widgets/html-manager/node_modules/@jupyterlab/rendermime/lib/mimemodel").MimeModel'.
      Types have separate declarations of a private property '_callback'.

83     wManager = new WidgetManager(context, rendermime, SETTINGS);
                                             ~~~~~~~~~~


Found 6 errors.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
</pre>
</details>

**Comment by echarles** [comment]
@chetan8300 Thank you very much for trying out jupyter-react.

I was facing recently those issues while creating a fresh env., especially since we depend on the `next` (latest, greatest and sometimes buggy version https://github.com/datalayer/jupyter-react/blob/7b107d547e165152431c6f555560d64607590d5e/package.json#L47).

The root is on the upstream jupyterlab repo. I have opened https://github.com/jupyterlab/jupyterlab/issues/12345 to track this and https://github.com/jupyterlab/jupyterlab/pull/12346 to fix it. We will need to wait some days/weeks before an official next release.

In the meantime, you can fix it manually changing the node_modules javascript (not ideal, but very small action to make it work). I use `vi node_modules/@jupyterlab/completer/lib/widget.d.ts +56` and change   `set showDocsPanel(showDoc: boolean | null);` to `set showDocsPanel(showDoc: boolean);`

Hope this works for you.

**Comment by chetan8300** [comment]
@echarles Thanks a lot. It helps. There were still a few errors in these files: FileBrowserAdapter: Line 63, NotebookAdapter: Line 129, ConsoleAdapter: Line 37. But it's manageable.

**Comment by echarles** [comment]
I have just given a try from a blank page with the following and it works fine on my local env (MacOS)

```bash
# Clone this repository.
git clone https://github.com/datalayer/jupyter-react.git && \
  cd jupyter-react
# Setup your development environment.
conda deactivate && \
  make env-rm # If you want to reset your environment.
make env && \
  conda activate jupyter-react
# Clean, install and build.
make clean install build
You can launch an example and hack the source code. The changes will build automatically and will be available in your browser.
# Start the example.
echo open http://localhost:3208
yarn start
```

**Comment by echarles** [comment]
A new jupyterlab alpha release with the fix is planned for tomorrow.

**Comment by chetan8300** [comment]
@echarles It worked for me as well. Thanks. Let's try with alpha release tomorrow.
