### ISSUE TITLE
Missing  jupyter-docusaurus Repository mentioned in `README.md`

### ISSUE THREAD

**Issue by belanasaikiran** [datalayer/jupyter-react#19]
I am checking if the Jupyter-react can be implemented on a project I'm working for code-editors and found this repository. But for using this package the `jupyter-docusaurus` seems to be missing. Either It would've been removed or it was now made a private repo. 

Could you please check and update the documentation.

Thank you,
Saikiran Belana

**Comment by echarles** [comment]
@belanasaikiran Thx for the interest. `jupyter-docusaurus` was a separate repository and now lives in the [examples folder](https://github.com/datalayer/jupyter-react/tree/main/examples/docusaurus).

> I am checking if the Jupyter-react can be implemented on a project

For now, it is safer to build from source and play in the source code of the examples. The latest npm published version is outdated for now.

**Comment by belanasaikiran** [comment]
Thank you @echarles. I'll check the `examples` folder

**Comment by echarles** [comment]
@belanasaikiran A few things had to be fixed further to the merge of the examples repositories. To try out, just run the following commands. Happy to know if it worked for you and to help in case of any question/request.

```bash
# Clone the jupyter-react repository.
git clone https://github.com/datalayer/jupyter-react.git && \
  cd jupyter-react
# Setup your development environment.
conda deactivate && \
  make env-rm # If you want to reset your environment.
make env && \
  conda activate jupyter-react
# Clean, install and build.
make clean install build
# You can start an example and hack the source code.
# The changes will build automatically and will be available in your browser.
echo open http://localhost:3208
yarn start
# We have other examples, pick one of the following commands.
yarn start:docusaurus # open http://localhost:3000
yarn start:lexical    # open http://localhost:3000/docs/intro
yarn start:slate      # open http://localhost:3266
```
