### ISSUE TITLE
 Integration error with react application

### ISSUE THREAD

**Issue by nagarjunayadavk** [datalayer/jupyter-react#21]
## Description

 I have created a react app (using create-react-app) and trying to integrate python terminal using **@datalayer/jupyter-react**  package getting below issues. 

 I have followed the steps below for JavaScript and Typescript. Can you please help anything wrong here?

- created a react app using create-react-app yarn package.
- added packages react-redux, redux and @datalayer/jupyter-react
- Started **Jupyter lab with port ****(ex:8686) using dev/config/jupyter_server_config.py file - jupyter-lab --config=dev/config/jupyter_server_config.py**
- added below code in index.html page.

```
  <script id="datalayer-config-data" type="application/json">
      {
        "jupyterServerHttpUrl": "http://localhost:8686//api/jupyter",
        "jupyterServerWsUrl": "ws://localhost:8686//api/jupyter",
        "jupyterToken": "60c1661cc408f978c309d04157af55c9588ff9557c9380e4fb50785750703da6"
      }
    </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js"></script>
```

- added below code in App.js to render Jupyter Cell in DOM as show in bellow           

```
 <Jupyter terminals={false} collaborative={false}>
  <CellExample />
</Jupyter>
```
              OR
```
<Jupyter terminals={true} collaborative={true}>
  <CellExample />
</Jupyter>
```
CellExample implemented the same as given examples in [repo](https://github.com/datalayer/jupyter-react/blob/main/packages/react/src/examples/components/cell/CellExample.tsx).       

**UI Screen Error:**

<img width="777" alt="image_1" src="https://user-images.githubusercontent.com/3591072/182640701-b5e164b3-3274-4ca4-ad71-1a9dcef343ee.png">

 **Errors in Console:**  

<img width="848" alt="image_2" src="https://user-images.githubusercontent.com/3591072/182640887-cff84bf0-7c9f-41f0-a1e3-b0a39ba2dec9.png">

Thanks!

**Comment by echarles** [comment]
Thx a lot @nagarjunayadavk 

We have just pushed a new release in npm and setup an example repository for a create-react app https://github.com/datalayer/jupyter-react-example. As you will see in the README of that repository, there are a few actions to be taken once the create-react app is created. You can start by just cloning and testing that repository which should work. If you are running on windows, please convert the remove commands of the Makefile.


@amantham20 you may also be interested in the example repository https://github.com/datalayer/jupyter-react-example. On https://github.com/amantham20/athena you write `Current Status: Halted (due to dependacy incomability)`, I hope this can unblock you. Otherwise, please open any issue here, we will jump to help.

**Comment by nagarjunayadavk** [comment]
@echarles thanks for your support. I am able to run the code now and able to see python code runner.

can you please help with the issues below.

1. I am unable to see Cell commands (such as run, interrupt, restart etc.) as shown in image1 below. As you see in the screenshots below, image2 has these commands displayed as expected. I am not sure that the issue is. 
   when **@datalayer/jupyter-react** package integrate with react app not able see **Cell commands**.
   I have analyzed and able to see  DOM generated for **run, interrupt, restart, status** as buttons but inside that  no **svg** image are generated when I compare with **jupyter-react** project run locally.
 do I need to add any other packages?
@image1
<img width="947" alt="image" src="https://user-images.githubusercontent.com/3591072/183366730-ac762f6c-8f22-4ab5-ba4a-e78bf571f824.png">

**when jupyter-react application runs:**
@image2
<img width="954" alt="image" src="https://user-images.githubusercontent.com/3591072/183366112-cc46c986-f641-410b-9c01-708e5771c871.png">

3. How to control **cellActions** like execute, source, outputsCount, update?.
  I have to create my custom buttons/UI an take control of **cellActions** similar to CellToolbar.js(https://github.com/datalayer/jupyter-react/blob/main/packages/react/src/examples/components/cell/CellToolbar.tsx)
   
   <img width="233" alt="image" src="https://user-images.githubusercontent.com/3591072/183369444-68d1078b-0b49-4e56-90d6-bb7ac28d2575.png">


Thanks!

**Comment by echarles** [comment]
>  I am unable to see Cell commands

Which browser are you using? Chrome should display the cell toolbar from the beginning.

> when jupyter-react application runs:

Are you saying you see the cell toolbar after the code has been run?

> How to control cellActions like execute, source, outputsCount, update?.

Just take inspiration from the code you have linked. You have to run `onClick={() => dispatch(cellActions.execute())}`

**Comment by nagarjunayadavk** [comment]
> Which browser are you using? Chrome should display the cell toolbar from the beginning.

I am using Chrome but not able see cell toolbar.

> Are you saying you see the cell toolbar after the code has been run?

No. I have cloned [jupyter-react](https://github.com/datalayer/jupyter-react) repository and development setup done locally.

**Comment by echarles** [comment]
@nagarjunayadavk Just upgrade to latest jupyterlab and codemirror. The cell toolbar should now be displayed by default (changed also the CSS for that).

**Comment by nagarjunayadavk** [comment]
@echarles still I am unable to see Cell commands.

**Comment by echarles** [comment]
Can you try in devtool to add `!important` to the height or visibility CSS attributes?

**Comment by nagarjunayadavk** [comment]
@echarles I have tried this and not working.
I have analyzed and able to see DOM generated for **run, interrupt, restart, status** as buttons but inside that there is no **text or svg images are generated** 

<img width="956" alt="image" src="https://user-images.githubusercontent.com/3591072/184527439-5142c7ea-3ac8-4322-b8b6-3f0b30c53aca.png">

**Comment by echarles** [comment]
@nagarjunayadavk how are you progressing? Are you still blocked with this?

**Comment by echarles** [comment]
@nagarjunayadavk We have done a few releases since then, which is being used successfully by various users. I will close this issue for now. Please feel free to open new ones with any specific question or issue you would face. Thank you again for trying out.
