### ISSUE TITLE
Specify the correct way to use Notebook

### ISSUE THREAD

**Issue by dbhagesh** [datalayer/jupyter-react#22]
### Problem
I tried to use the Notebook component of Jupyter-react. But using it as mentioned in the documentation resulted in just plain white screen.

This is the way I am using it.
![image](https://user-images.githubusercontent.com/32410360/186464580-688e05e7-2332-4ea1-aad9-fe0833047313.png)

Can someone please guide me to the correct usage ?

**Comment by echarles** [comment]
Thx @dbhagesh for trying out.

Have you a successful setup (install and build) following https://github.com/datalayer/jupyter-react#contribute. I have just pushed a few fixed, so if you are using a version of today, please pull the latest commits.

Once you are confident with your env, you can run the code you show (maybe start with collabortive={false}).

You can report error messages shown in the browser devtool console.

**Comment by ankitkumarbrur** [comment]
### Facing same issue while using `notebook` from `'@datalayer/jupyter-react'`

_My `App.tsx` file_
```
import { Jupyter, Notebook } from '@datalayer/jupyter-react';

import './App.css';

function App() {
  return (
    <>
      <Jupyter terminals={true} collaborative={false}>
        <Notebook
          path='ping.ipynb'
        />
      </Jupyter>
    </>
  );
}

export default App;
```
I am getting this as output. Not able to load the specified `ping.ipynb` file. Also I didn't face any error while building the env. 
![image](https://user-images.githubusercontent.com/38562921/186653088-9f2bbe29-784e-4625-90e4-ac7fccd690d0.png)

**Comment by echarles** [comment]
@ankitkumarbrur jupyter-react will try to connect to the jupyter server defined in the html page (you can override that by passing explicit props via the Jupyter context) https://github.com/datalayer/jupyter-react/blob/aa7fcac56381d53e701b1516120f51781998214e/packages/react/public/index.html#L4-L10

Are you using the provided scripts in the `dev` folder or are you using your own jupyter server. In both case, the ipynb you define has to be served by the jupyter server. To be sure, you can invoke the server directly from your browser.

**Comment by ankitkumarbrur** [comment]
I am able to execute cells and the jupyter server is working but it is not loading cells from specified `ipynb` file in `path`. Each time I refresh it loads a blank notebook.

**Comment by echarles** [comment]
> I am able to execute cells and the jupyter server is working but it is not loading cells from specified ipynb file in path. Each time I refresh it loads a blank notebook.

@ankitkumarbrur Thx a lot for reporting. You are correct, this is a regression. I have committed a fix https://github.com/datalayer/jupyter-react/commit/29e51b77e7f2f8783794a912019230a362dab059. Can pull and try again if it works for you?
