### ISSUE TITLE
Bug in Example : Create-react-app 

### ISSUE THREAD

**Issue by dbhagesh** [datalayer/jupyter-react#23]
## Description
While running the example/create-react-app I am getting an error "Cannot find module '@datalayer/jupyter-react' or its corresponding type declarations"
I followed the steps as mentioned in the Readme file.

![image](https://user-images.githubusercontent.com/32410360/186467273-21a47253-28b7-4458-86c8-e18a991d60d4.png)

## Reproduce

1. Clone jupyter-react
2. Change directory to example/create-react-app
3. Follow the readme steps
4. yarn start

**Comment by echarles** [comment]
I have just pushed an update to the README of the create-react-app example. You first need to setup the environment and ensure the `make install build` works fine. You can then try with `yarn start` which should give you the following content browsing http://localhost:3208. Only after you can `cd example/create-react-app && yarn start`.

<img width="1178" alt="Screenshot 2022-08-24 at 18 25 49" src="https://user-images.githubusercontent.com/226720/186472475-a417b703-1279-4133-924f-b30db0655b28.png">

Hope this helps.

**Comment by dbhagesh** [comment]
Thankyou for your help. It's working now.
![image](https://user-images.githubusercontent.com/32410360/186487210-f9f12b9f-5fc2-42e2-8653-d0f7d8bc8814.png)
I was getting this error.
And when I checked the 'Makefile'. I found that its installing the 0.1.17 version. But it requires 0.1.10
Either comment this line or install the required version. 
It got resolved after doing so.
