### ISSUE TITLE
Update the jupyter-react npm package to v0.0.11 on npm website

### ISSUE THREAD

**Issue by dbhagesh** [datalayer/jupyter-react#24]
Currently v0.0.10 is present here.
https://www.npmjs.com/package/@datalayer/jupyter-react

Please update it to the latest 0.0.11.

**Comment by echarles** [comment]
I will wait until tomorrow for any feedback on https://github.com/datalayer/jupyter-react/issues/25

If you have other needs, please open issue, I will have a look and try to implement it if possible.

**Comment by echarles** [comment]
@dbhagesh `@datalayer/jupyter-react@0.0.13` is released in npm (skip the 0.0.11 and 0.0.12 versions). It contains the load/save notebook feature.

Please close this issue if it works for you.
