### ISSUE TITLE
Save Button present in Notebook Toolbar is not saving the Notebook.

### ISSUE THREAD

**Issue by dbhagesh** [datalayer/jupyter-react#25]
## Description
While working on Notebook, pressing the save button doesn't write/save the changes made to the Notebook.
The Save Action present in the package is just tracking the changes but not writing them to the Notebook.

## Reproduce

1. Open any Notebook with NotebookSidebarExample component.
2. Make some changes and press save button.
3. An redux action is dispatched with "notebookActions.save" action
4. It writes to the store but doesn't write to the Jupyter server where the file is present.

## Expected behavior

The "notebookActions.save" action should save the changes to the Jupyter Server.
Maybe we can integrate the Jupyter APIs to save the file ,create one etc
https://jupyter-server.readthedocs.io/en/latest/developers/rest-api.html

**Comment by dbhagesh** [comment]
![image](https://user-images.githubusercontent.com/32410360/187030710-8be4f2f7-48c1-4d4f-9cd3-c95e3edf0a11.png)

We can use this API, to update the file with the new content.

**Comment by echarles** [comment]
@dbhagesh This is implemented in https://github.com/datalayer/jupyter-react/commit/70842298671478001c8ae0a714c0a5173ec45d6d Save commands were already available and just needed to be triggered. Those commands post indeed to the jupyter server API you have referenced. Thx!

**Comment by dbhagesh** [comment]
I checked the commit you mentioned above. 
But the latest repository doesn't contain the "saveEpic" which is present in the commit you mentioned above.
And while testing the latest repository I found that save button is not functioning. 
Can you include the relevant functions in the latest commit so that the save function will be back in the latest v0.0.11.
Please specify if I am missing anything.
Thankyou

**Comment by echarles** [comment]
The `saveEpic` is present in latest main branch https://github.com/datalayer/jupyter-react/blob/f7a5de96604598a975dc3b3c407751e9c0ef3216/packages/react/src/components/notebook/NotebookState.ts#L279-L295

I have pushed more fixes to ensure the jupyter server answer is not cached. Could you pull the latest commits and try again. Thank you very much for trying out, this is very helpful. Nothing is shown for now when you click on the `Save` button in the example, but you can check that the HTTP request in the devtools is successful. If you refresh your browser, you can also check that the change is saved.

I reopen this issue.

**Comment by dbhagesh** [comment]
Yes, its working for local environment containing the v0.0.14 (LATEST ON GITHUB).
But the remote dependency i.e v0.0.13 still lacks the save feature. No, API call is made for save button in this version.
It will be better if you could host the latest version so that [241b0](https://github.com/datalayer/jupyter-react/commit/d1bc0a6691277571221de233470fd0f964e241b0) changes are available remotely.

Thankyou for the help.

**Comment by echarles** [comment]
I can cut a new release, but 0.0.13 should contain the fix. I will cut anyway a new release tomorrow. Thx for the very useful feedback so far and glad that you find jupyter-react usable and useful.

**Comment by dbhagesh** [comment]
Yes, you are correct. This isn't the version problem which I am facing.
Actually, I have separated the "create-react-app" and "Jupyter-react".
And I am starting the "Jupyter-react" server from the main application. And just starting the react part of the "create-react-app".
And if I am doing so, then the "jupyter-react" server is not started from the create-react-app/dev section. Instead it is started from the main application.
Under the above scenario, everything is working fine except save button. No API call is made in this situation when I click on save.
You may test in the above situation.
Suggestion, separate the "Create-react-app" from "jupyter-react" server. And let the "jupyter-react" server and frontend be independent.
Thankyou for your help again.

**Comment by echarles** [comment]
@dbhagesh I have tested the scenario you describe (start the server from the top, and start the create-react-app from the subfolder) and it works fine.

I have pushed an update to the create-app example to add a notebook with a toolbar with the save button. It is working on my env (the changes to the notebook are saved).

**Comment by dbhagesh** [comment]
@echarles Yes, its working fine that way. But if you move the create-react-app folder outside the main application, then the save part doesn't work.

**Comment by echarles** [comment]
@dbhagesh I have tested in the scenario you describe (moving create-react-app example in a folder outside of the repo, `yarn install` that folder, start the server from the repo, start the react-app from the folder) and indeed the save was not working with jupyter-react@0.0.13. This is because the current example provides a parameter (a date) and in the 0.0.13 version, you had to give undefined for the save to be effective. I have change to the following code, and it is saving fine with 0.0.13.

```react
          <Button
            variant="default"
            size="small"
            onClick={() => dispatch(notebookActions.save.started(undefined))}
            >
              Save the notebook
          </Button>
```

**Comment by echarles** [comment]
`0.0.14` is now published and saves whatever (date or undefined) you pass to the `save.started(...)` function.

I hope this will work for you.

**Comment by dbhagesh** [comment]
Yes, its finally working :smiley:
Thank you for your help.
I am closing the issue now.
