### ISSUE TITLE
Failure to render Notebook with create-react-app

### ISSUE THREAD

**Issue by peytondmurray** [datalayer/jupyter-react#26]
## Description

Rendering a notebook in a create-react-app fails, with errors related to themes and invalid hook calls. Looks like this may have been solved in #21, but I'm using a newer version of `jupyter-react`.

## Reproduce

Here's a minimal working example: https://github.com/peytondmurray/jupyter-react-cra-example

1. `yarn create react-app testapp --template typescript`
2. Removed some of the CRA assets: `manifest.json` and the svg logos. Add a `test.ipynb`.
3. Insert a `Jupyter` component with a `Notebook` component inside. Start a jupyter server and copy the token into the component.
4. There are a few missing packages at this point, so install them now: `yarn add @emotion/react @emotion/styled @mui/styled`
5. `yarn start`; the server will start up without an issue, but the page doesn't render. There are a few separate errors here:

* `Invalid hook call`

![image](https://user-images.githubusercontent.com/14017872/188942466-41f371aa-c6d0-40e5-a7d1-75db9b3ea1b0.png)

* Theme-related errors: 

![image](https://user-images.githubusercontent.com/14017872/188943353-25346da0-d00d-49f8-b945-7311d6778f96.png)

The same errors appear whether I wrap the `Jupyter` component in a `ThemeProvider` component or not.

## Expected behavior

The notebook should render.

## Context

- Datalayer version: 0.0.14
- Operating System and version: Linux 5.19.7
- Browser and version: `Version 105.0.5195.102 (Official Build) Arch Linux (64-bit)`

**Comment by echarles** [comment]
I will further look tomorrow, but I already see that block is an issue https://github.com/peytondmurray/jupyter-react-cra-example/blob/d25503ea6a22ca1df591876d7094e7875147639c/src/App.tsx#L21

It should be the path of a notebook on the jupyter server, not the path of the local file in the react app.

**Comment by echarles** [comment]
On https://github.com/peytondmurray/jupyter-react-cra-example/blob/d25503ea6a22ca1df591876d7094e7875147639c/src/App.tsx#L17 for the websocket URL you should set `ws://localhost:8888/api/jupyter` and not `http://localhost:8888/api/jupyter` (ws protocol).

Can you pin the `react`, `react-dom` and `jupyterlab` versions  (in dependencies and resolutions) as documented on https://github.com/datalayer/jupyter-react/tree/a7b9c2362e36ed561d831829dfe925e8fe1d4535/examples/create-react-app#reactjs-version-resolutions and https://github.com/datalayer/jupyter-react/tree/a7b9c2362e36ed561d831829dfe925e8fe1d4535/examples/create-react-app#jupyterlab-version-resolutions.

Finally, can you upgrade to jupyter-react version 0.0.15? (made a few changes for better default props).

**Comment by peytondmurray** [comment]
@echarles Thanks for the help, I've upgraded `jupyter-react` to `0.0.15` now.

One thing I noticed: `jupyter-react` depends on `react 18.1.0` and `@jupyterlab/apputils 4.0.0-alpha.13` which depends on `react ^17.0.1`. This means that the resolutions

```json
  "dependencies": {
    "react": "18.1.0",
    "react-dom": "18.1.0"
  },
  "resolutions": {
    "**/@types/react": "18.0.9",
    "**/@types/react-dom": "18.0.5",
    "**/react": "18.1.0",
    "**/react-dom": "18.1.0"
  },
```

can't be satisfied for these dependencies. As a result, I get

```
warning Resolution field "react@18.1.0" is incompatible with requested version "react@^17.0.1"
```

upon doing `yarn install`. In any case, I'm still testing to see if I can get this to render - will update in a few if I have success. Thanks again for the support!

**Comment by echarles** [comment]
Yes, this is a trade-off. Warning will be shown on install, but at compile and runtime, this is perfectly fine as React 18 is backwards compatible with React 17.

Please add more resolutions for jupyterlab as documented on https://github.com/datalayer/jupyter-react/tree/a7b9c2362e36ed561d831829dfe925e8fe1d4535/examples/create-react-app#jupyterlab-version-resolutions (to alpha.12) otherwise the brand new Lumino 2 alpha (a few days ago) will be pulled in  but alpha.13 and may give issues. I plan to upgrade to alpha.13 in a few days.

Looking forward your progress on this initial step.

**Comment by peytondmurray** [comment]
Okay, I added all the resolutions and dependencies from [here](https://github.com/datalayer/jupyter-react/tree/a7b9c2362e36ed561d831829dfe925e8fe1d4535/examples/create-react-app). There are still dependency resolution problems, e.g. `jupyter-react` depends on `@jupyterlab/services@7.0.0-alpha.12` and `@jupyter-widgets/base@6.0.0-rc.1`. But `@jupyter-widgets` depends on `@jupyterlab/services@^6.0.0` but maybe this isn't an issue.

In any case, adding those dependencies and resolutions was helpful. I've also fixed the websocket URL, and am now launching the jupyter server using the `jupyter_server_config.py` from your CRA example. Now when I `yarn start` and visit `https://localhost:3000`, kernels start and some notebook-related stuff appears in the DOM, but nothing renders:

![image](https://user-images.githubusercontent.com/14017872/189205832-29ca1662-3889-4e5c-a2b0-a36006a14fc3.png)

So now at least we know we're talking to the server correctly! However, I'm still getting invalid hook call errors even after adding those resolutions:

![image](https://user-images.githubusercontent.com/14017872/189205755-91a2db19-6e6b-492f-aea0-8349ab77724a.png)

[Here's the MWE for reference, updated with your suggestions.](https://github.com/peytondmurray/jupyter-react-cra-example)

**Comment by echarles** [comment]
Is the notebook accessible via http://localhost:8888/api/jupyter/api/contents/test.ipynb? ?

> and am now launching the jupyter server using the jupyter_server_config.py

Can you check the token you use in the react app are the same as the one defined in the config? 

<img width="700" alt="Screenshot 2022-09-08 at 21 56 04" src="https://user-images.githubusercontent.com/226720/189214032-7979872d-3120-43ef-a8e3-500fcf649c80.png">

This is the exact same error I had this morning because on jupyterlab beta.13 using some new iterator not supported by Lumino 1. Can you double check the resolutions of jupyterlab and which ones is effectivelly present in your node_modules?  You should have only alpha.12 a and lumino 1.x

**Comment by peytondmurray** [comment]
> Is the notebook accessible via http://localhost:8888/api/jupyter/api/contents/test.ipynb? ?

Yes, it is available at http://localhost:8888/api/contents/test.ipynb. The address is a bit different than yours because my `jupyter_server_config.py` is using the defaults for the `ServerApp.base_url` and `ServerApp.default_url`, rather than `/api/jupyter/`, but that should be fine.

> Can you check the token you use in the react app are the same as the one defined in the config?

Yeah, I double checked this just now - I've copied the token directly from the `jupyter_server_config.py` to `App.tsx`, so it's the same.

> This is the exact same error I had this morning because on jupyterlab beta.13 using some new iterator not supported by Lumino 1. Can you double check the resolutions of jupyterlab and which ones is effectivelly present in your node_modules? You should have only alpha.12 a and lumino 1.x

Definitely, here's my [yarn.lock](https://github.com/datalayer/jupyter-react/files/9530286/yarn.lock.zip) (you'll have to unzip it). Looks like it resolved to `4.0.0-alpha.12`:

```
"@jupyterlab/application@4.0.0-alpha.12", "@jupyterlab/application@^3.0.0", "@jupyterlab/application@^4.0.0-alpha.12":
  version "4.0.0-alpha.12"
  resolved "https://registry.yarnpkg.com/@jupyterlab/application/-/application-4.0.0-alpha.12.tgz#c963ce01f1025973fbad46f2b6ccc0cc8d51913b"
  integrity sha512-n6/fbNgQ95Nt+h11RaVBLDH2KAaSwOpWNlMJE10FqLVwC1ocHfULSLqMm78pn2NjMG2xHvyVgGO71wc52nBxBQ==
  dependencies:
    "@fortawesome/fontawesome-free" "^5.12.0"
    "@jupyterlab/apputils" "^4.0.0-alpha.12"
    "@jupyterlab/coreutils" "^6.0.0-alpha.12"
    "@jupyterlab/docregistry" "^4.0.0-alpha.12"
    "@jupyterlab/rendermime" "^4.0.0-alpha.12"
    "@jupyterlab/rendermime-interfaces" "^3.8.0-alpha.12"
    "@jupyterlab/services" "^7.0.0-alpha.12"
    "@jupyterlab/statedb" "^4.0.0-alpha.12"
    "@jupyterlab/translation" "^4.0.0-alpha.12"
    "@jupyterlab/ui-components" "^4.0.0-alpha.27"
    "@lumino/algorithm" "^1.9.1"
    "@lumino/application" "^1.29.0"
    "@lumino/commands" "^1.20.0"
    "@lumino/coreutils" "^1.12.0"
    "@lumino/disposable" "^1.10.1"
    "@lumino/messaging" "^1.10.1"
    "@lumino/polling" "^1.10.0"
    "@lumino/properties" "^1.8.1"
    "@lumino/signaling" "^1.10.1"
    "@lumino/widgets" "^1.33.0"
```

**Comment by echarles** [comment]
@peytondmurray Instead of fighting the new jupyterlab alpha version and breaking-change lumino 2, I have decided to embrasse them. I have released jupyte-react 0.0.16 and opened https://github.com/peytondmurray/jupyter-react-cra-example/pull/2 which works for me (running notebook in the browser). Can you give a try to that PR and tell me the outcome on your env? Thx again for your confidence while working in these moving sands, I feel you have just started at a breaking time coming from the lasted jupyterlab releases.

**Comment by peytondmurray** [comment]
@echarles Thanks, the new release and the changes you introduced with that PR were enough to get the notebook to render and for me to be able to use it. Thank you so much!

![image](https://user-images.githubusercontent.com/14017872/189413452-de8b2585-ed49-4648-b1ae-de63804be2fc.png)

A few errors still show up in the console, but they're not blocking me as far as I can tell:

1. `react-dom.development.js:84 Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17.` I did a quick grep of the jupyter-react source and I don't see any calls to `ReactDOM.render` anywhere except once in `experiments/css/src/index.tsx`, which just looks like an example app. So I'm guessing that's not the code that generates the error in the console log. :shrug:
2. `Store does not have a valid reducer. Make sure the argument passed to combineReducers is an object whose values are reducers.` There's zero information in this error message about where in `jupyter-react` the problem is. Without knowing more about where and how redux is used in `jupyter-react`, I don't know how helpful I can be in tracking this one down.
3. `Warning: Invalid hook call...` Again, somehow there's no information about _which_ hook call is invalid or where I can find it in the jupyter-react source, but I thought I'd mention it here anyway just so the issue can be tracked.

**Comment by echarles** [comment]
> @echarles Thanks, the new release and the changes you introduced with that PR were enough to get the notebook to render and for me to be able to use it. Thank you so much!

That is great news! Excited to see that.

> react-dom.development.js:84 Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17.

These are being generated by JupyterLab react widgets wrapped into Lumino. I can not do much for that for now.

> Store does not have a valid reducer. Make sure the argument passed to combineReducers is an object whose values are reducers. 

That is something that will be soon fixed. It is a runtime warning when creating the redux store, which is injected injected based on the components that are requested to be displayed.

> Warning: Invalid hook call...

mmh I will investigate those warnings.

**Comment by echarles** [comment]
@peytondmurray If this works for you, can you close this issue? Thx.

**Comment by peytondmurray** [comment]
Yep, thanks!
