### ISSUE TITLE
Multiple Entity is Created of Default Sidebar Buttons

### ISSUE THREAD

**Issue by dbhagesh** [datalayer/jupyter-react#27]
## Description
I am using Jupyter-React Notebook as a component to render multiple notebooks in different panes (Simple ANT DESIGN PANE/WINDOW).
But if multiple notebooks are brought into exitence multiple sidebar buttons are attached for each cell.

My simple component
![image](https://user-images.githubusercontent.com/32410360/190155519-75c2ecf4-bc01-43aa-a012-84e212bf6a56.png)

The way it looks. Here each cell got two set of sidebar buttons.
If I open 'x' notebooks in different pan. I am getting 'x' different set of sidebar buttons.
![image](https://user-images.githubusercontent.com/32410360/190155600-117d3542-a709-4419-bb97-70b2994dc9f2.png)

Here is the DOM (dla-CellHeader-Container)
![image](https://user-images.githubusercontent.com/32410360/190155840-f5d34b18-0424-4b57-81d4-d3a831ef92d2.png)

I suggest that whenever side buttons are brought into existence. It must be checked that if the buttons are already in existence for that cell or not. And only after that a new set of sidebar buttons should be attested.

Looking forward for your guidance.

**Comment by dbhagesh** [comment]
By the way,
Happy 50 stars :smile:

**Comment by echarles** [comment]
@dbhagesh Thx!

We do support multiple outputs in one single context, but not yet multiple notebooks. This should not be hard to implement and should resolve the issue you are reporting. I am just travelling to US tomorrow, so it may take a few days to get this out. Thx for your patience.

**Comment by dbhagesh** [comment]
Yes, sure.

**Comment by dbhagesh** [comment]
@echarles 
I'm sure you must be really busy, and I don't want to seem interrupting.
Hope you can find a few minutes on this. Appreciate your time.

**Comment by dbhagesh** [comment]
I tried to dig into the problem.
The main problem is whenever multiple notebooks are rendered. Then the portals are filled up with sidebar DOM element for each cell.
The problem occurs the moment the portals are rendered.
Portals contain all the cells for every notebook.
So, if the Notebook component is fired 3 times.
The portals will be rendered 3 times. 
Ultimately forcing 3 entities for sidebar buttons.

I think if we make the notebook states independent of each other in redux will solve the problem.
Like instead of using a single notebook state for 'x' notebooks, we can create 'x' states for 'x' notebooks in react.

**Comment by echarles** [comment]
jupyter-react 0.0.20 fixes this. Be sure to provide a `uid` property to the notebook, and reuse that property when triggering Redux actions (the API has slightly changed to support this, have a look at [the examples](https://github.com/datalayer/jupyter-react/tree/884d61c6066e84862ff70bf0b4a6961efeb3e7fb/packages/react/src/examples)).

**Comment by dbhagesh** [comment]
Yes, its perfect now. 
Thanks @echarles
