### ISSUE TITLE
Notebook should resize when browser/window is resized

### ISSUE THREAD

**Issue by echarles** [datalayer/jupyter-react#28]

**Comment by dbhagesh** [comment]
I have a work around for this.
CSS of the Notebook is overridden here.
AntD classes can be ignored. Rest of them should solve the problem
Take care that the container is set to 100% for both attributes height and width.


    /*
    General CSS Fix
    */

    .lm-Widget.p-Widget.jp-MainAreaWidget.jp-NotebookPanel.lm-BoxPanel-child.p-BoxPanel-child {
        .lm-Widget.p-Widget.jp-Notebook.jp-mod-scrollPastEnd.jp-mod-showHiddenCellsButton.jp-NotebookPanel-notebook.jp-mod-commandMode {
            top: 0px !important;
            height: 100% !important;
        }

        .lm-Widget.p-Widget.jp-Notebook.jp-mod-scrollPastEnd.jp-mod-showHiddenCellsButton.jp-NotebookPanel-notebook.jp-mod-editMode {
            top: 0px !important;
        }
    }

    div.lm-Widget.jp-MainAreaWidget.jp-NotebookPanel.lm-BoxPanel-child {
        width: 100% !important;
    }

    div.lm-Widget.jp-Notebook.jp-mod-scrollPastEnd.jp-mod-showHiddenCellsButton.jp-NotebookPanel-notebook.jp-mod-commandMode {
        top: 0px !important;
        height: 100% !important;
        width: 100% !important;
        overflow: scroll !important;
    }

    div.lm-Widget.jp-Notebook.jp-mod-scrollPastEnd.jp-mod-showHiddenCellsButton.jp-NotebookPanel-notebook.jp-mod-editMode {
        top: 0px !important;
        height: 100% !important;
        width: 100% !important;
        overflow: scroll !important;
    }

    div.Box-sc-1gh2r6s-0 {
        height: 100% !important;
        width: 100% !important;

        div {
            height: 100% !important;
        }
    }

    div.Box-sc-1gh2r6s-0.css-2tgqaj-Notebook {
        height: 100% !important;
    }

    div.lm-Widget.lm-Panel.lm-BoxPanel.dla-JupyterLab-Notebook {
        height: 100% !important;
    }

    div.lm-Widget.jp-Cell.jp-MarkdownCell.jp-mod-rendered.jp-Notebook-cell.jp-mod-active.jp-mod-selected {
        height: unset !important;
    }

    div.lm-Widget.jp-Cell.jp-MarkdownCell.jp-mod-rendered.jp-Notebook-cell {
        height: unset !important;
    }

    div.lm-Widget.jp-Cell.jp-CodeCell.jp-mod-noOutputs.jp-Notebook-cell.jp-mod-active.jp-mod-selected {
        height: unset !important;
    }

    div.lm-Widget.jp-Cell.jp-CodeCell.jp-mod-noOutputs.jp-Notebook-cell {
        height: unset !important;
    }

    div.lm-Widget.jp-Cell.jp-MarkdownCell.jp-Notebook-cell.jp-mod-active.jp-mod-selected {
        height: unset !important;
    }

    div.lm-Widget.jp-Cell.jp-MarkdownCell.jp-Notebook-cell {
        height: unset !important;
    }

    div.lm-Widget.jp-Cell.jp-CodeCell.jp-Notebook-cell.jp-mod-active.jp-mod-selected {
        height: unset !important;
    }

    div.lm-Widget.jp-Cell.jp-CodeCell.jp-Notebook-cell {
        height: unset !important;
    }

    div.lm-Widget.jp-CellHeader.jp-Cell-header {
        height: auto !important;
    }


    .Pane {
        height: 100% !important;
    }

    div.ant-tabs.ant-tabs-top.ant-tabs-editable.ant-tabs-card.ant-tabs-editable-card {
        height: 100% !important;
    }

    div.ant-tabs-content.ant-tabs-content-top {
        height: 100% !important;
    }

    div.ant-tabs-tabpane.ant-tabs-tabpane-active {
        height: 100% !important;
    }

    div.BaseStyles__Base-sc-nfjs56-0.gUfnxs {
        height: 100% !important;
    }

    div.BaseStyles__Base-sc-nfjs56-0 {
        height: 100% !important;
    }

    div.BaseStyles__Base-sc-nfjs56-0.brIFCS {
        height: 100% !important;
    }

    div.lm-Widget.p-Widget.jp-Notebook.jp-mod-scrollPastEnd.jp-mod-showHiddenCellsButton.jp-NotebookPanel-notebook.jp-mod-commandMode {
        height: 100% !important;
    }

    div.lm-Widget.p-Widget.jp-Notebook.jp-mod-scrollPastEnd.jp-mod-showHiddenCellsButton.jp-NotebookPanel-notebook.jp-mod-editMode {
        height: 100% !important;
    }

    div.lm-Widget.p-Widget.jp-Notebook.jp-mod-scrollPastEnd.jp-mod-showHiddenCellsButton.jp-NotebookPanel-notebook.jp-mod-editMode {
        height: 100% !important;
    }

    div#id-fd3dcc5e-a2e8-40d7-9ade-dd6b9373b041.lm-Widget.p-Widget.jp-MainAreaWidget.jp-NotebookPanel.lm-BoxPanel-child.p-BoxPanel-child {
        height: 100% !important;
    }

    div#id-1b953030-ae64-4371-83f0-ea4b5d272842.lm-Widget.p-Widget.jp-MainAreaWidget.jp-NotebookPanel.lm-BoxPanel-child.p-BoxPanel-child {
        height: 100% !important;

        div#id-0e1e4cbc-c431-4ce8-b16f-2d7563d93f4a.lm-Widget.p-Widget.jp-Notebook.jp-mod-scrollPastEnd.jp-mod-showHiddenCellsButton.jp-NotebookPanel-notebook.jp-mod-commandMode {
            height: 100% !important;
        }
    }

    div.lm-Widget.p-Widget.jp-MainAreaWidget.jp-NotebookPanel.lm-BoxPanel-child.p-BoxPanel-child {
        height: 100% !important;
        width: 100% !important;
    }

    div.lm-Widget.p-Widget.jp-MainAreaWidget.jp-NotebookPanel.lm-BoxPanel-child.p-BoxPanel-child {
        height: 100% !important;
        width: 100% !important;

        div.lm-Widget.p-Widget.jp-Notebook.jp-mod-scrollPastEnd.jp-mod-showHiddenCellsButton.jp-NotebookPanel-notebook.jp-mod-commandMode {
            height: 100% !important;
            width: 100% !important;
        }
    }

**Comment by echarles** [comment]
@dbhagesh The CSS overrides would go in this Notebook.css file https://github.com/datalayer/jupyter-react/blob/b608e5abffb23c23c49a8edeeab804798802fb28/packages/react/src/components/notebook/Notebook.css

Would you have time to open a pull request to add those rules. I will be very happy. to review and merge.

**Comment by dbhagesh** [comment]
Yes, I created a pull request for the desired changes.
You may review and test it.

**Comment by echarles** [comment]
@dbhagesh I have merged https://github.com/datalayer/jupyter-react/pull/29 and followed-up with this commit ;https://github.com/datalayer/jupyter-react/commit/f4e1d28714d756d5cdf831d4b74fe0fdcd883f8d. Hope it still works in your case.

**Comment by dbhagesh** [comment]
Sorry, I wasn't available recently because of my University Exams. 
Will look what better I can do and update about it soon.

**Comment by echarles** [comment]
I think we are good now with latest commit, included your PR https://github.com/datalayer/jupyter-react/pull/32

I will close this issue, please reopen if it does not work for you.
