### ISSUE TITLE
[Upstream bug] React 18 support

### ISSUE THREAD

**Issue by peytondmurray** [datalayer/jupyter-react#39]
## Description

When loading a webapp with jupyter-react, a bunch of errors appear in the console saying that `ReactDOM.render is no longer supported in React 18. Use createRoot instead.`. This is due to the fact that JupyterLab does not yet support React 18, so this is currently an upstream bug.

![image](https://user-images.githubusercontent.com/14017872/194924594-f311fa97-08a2-4c91-b590-fbaec06187f0.png)

## Reproduce

The error can be recreated using this example repo: https://github.com/peytondmurray/jupyter-react-cra-example/tree/ad483c21d1b016ec37ce777d9b71ff1d6fbea40c. After starting the frontend and jupyter server, the error will appear on first page load.

## Expected behavior

The example above loads without errors.

## Context

- Datalayer version: 0.0.22
- Operating System and version: Linux 5.19.13-arch1-1 x86_64
- Browser and version: Firefox 105.0.2

<details><summary>Browser Output</summary>
<pre>
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
LuminoNotebook@http://localhost:3000/static/js/bundle.js:11868:7
div
O@http://localhost:3000/static/js/bundle.js:303820:6
div
O@http://localhost:3000/static/js/bundle.js:303820:6
withEmotionCache/<@http://localhost:3000/static/js/bundle.js:15108:66
div
Notebook@http://localhost:3000/static/js/bundle.js:6924:74
NotebookKernelChange@http://localhost:3000/static/js/bundle.js:5034:75
Provider@http://localhost:3000/static/js/bundle.js:277203:15
JupyterContextProvider@http://localhost:3000/static/js/bundle.js:10914:7
div
O@http://localhost:3000/static/js/bundle.js:303820:6
BaseStyles@http://localhost:3000/static/js/bundle.js:169613:7
Ge@http://localhost:3000/static/js/bundle.js:303731:60
ThemeProvider@http://localhost:3000/static/js/bundle.js:171061:7
ErrorBoundary@http://localhost:3000/static/js/bundle.js:274801:37
Jupyter@http://localhost:3000/static/js/bundle.js:10651:7
App 12 [react-dom.development.js:84](http://localhost:3000/home/pdmurray/Desktop/workspace/jupyter-react-cra-example/node_modules/react-dom/cjs/react-dom.development.js)
    React 3
    renderDOM vdom.js:69
    renderDOM vdom.js:62
    onUpdateRequest vdom.js:34
    processMessage index.es6.js:1443
    invokeHandler index.es6.js:453
    sendMessage index.es6.js:149
    onAfterAttach vdom.js:43
    processMessage index.es6.js:1485
    invokeHandler index.es6.js:453
    sendMessage index.es6.js:149
    onAfterAttach index.es6.js:2298
    processParentMessage index.es6.js:2183
    notifyLayout index.es6.js:1539
    processMessage index.es6.js:1484
    invokeHandler index.es6.js:453
    sendMessage index.es6.js:149
    onAfterAttach index.es6.js:2298
    processParentMessage index.es6.js:2183
    notifyLayout index.es6.js:1539
    processMessage index.es6.js:1484
    invokeHandler index.es6.js:453
    sendMessage index.es6.js:149
    onAfterAttach index.es6.js:2298
    processParentMessage index.es6.js:2183
    notifyLayout index.es6.js:1539
    processMessage index.es6.js:1484
    invokeHandler index.es6.js:453
    sendMessage index.es6.js:149
    attach index.es6.js:1945
    LuminoNotebook LuminoNotebook.js:15
    React 13
    renderDOM vdom.js:69
    renderDOM vdom.js:62
    onUpdateRequest vdom.js:34
    processMessage index.es6.js:1443
    invokeHandler index.es6.js:453
    sendMessage index.es6.js:149
    runMessageLoop index.es6.js:516
    (Async: FrameRequestCallback)
    enqueueMessage index.es6.js:477
    postMessage index.es6.js:208
    fit index.es6.js:1276
    set spacing index.es6.js:5264
    set spacing index.es6.js:5829
    NotebookAdapter NotebookAdapter.js:56
    Notebook Notebook.js:48
    React 8
    workLoop scheduler.development.js:260
    flushWork scheduler.development.js:234
    performWorkUntilDeadline scheduler.development.js:518
    (Async: EventHandlerNonNull)
    js scheduler.development.js:557
    js scheduler.development.js:614
    factory react refresh:6
    Webpack 24
</pre>
</details>

**Comment by echarles** [comment]
Thx for reporting. Latest JupyterLab 4.0.0a33 has bumped reac to version 18. I have updated jupyter-react to that new version and published version 0.0.24 which fixes this issue.

Closing as fixed.
