### ISSUE TITLE
Menu on /

### ISSUE THREAD

**Issue by echarles** [datalayer/jupyter-react#5]

**Comment by rowanc1** [comment]
You should check out https://github.com/curvenote/prosemirror-autocomplete!

![command-menu](https://user-images.githubusercontent.com/913249/140183228-9d467df1-d721-4594-bc47-5bff4569bfcf.gif)

I think you are also potentially using tiptap / prosemirror?

**Comment by echarles** [comment]
Hi @rowanc1. Thx for the link.

We are using Slate, and not Prosemirror. Both have IMHO similar capabilities. It is just a matter of choosing one of them and building on top.

**Comment by rowanc1** [comment]
Awesome -- maybe some inspiration or internals that might be helpful!
