### ISSUE TITLE
[WIP] JEP for React.js at Jupyter

### ISSUE THREAD

**Issue by echarles** [datalayer/jupyter-react#9]
This aims to create some content to be submitter as a JEP (Jupyter Enhancement Proposal) related to the usage of React.js in the Jupyter ecosystem.

The work preparation is being done in https://github.com/datalayer/jupyter-react/tree/jep/jep

Context:

- Jupyter for React.js developers https://fosdem.org/2022/schedule/event/lt_jupyter by @echarles 
- Component library for building web interfaces in Jupyter ecosystem (JupyterHub, Jupyter Widgets, JupyterLab,...) https://github.com/jupyterlab-contrib/jupyter-ui-toolkit by @fcollonval

**Comment by echarles** [comment]
@fcollonval I have pushed some more content on https://github.com/datalayer/jupyter-react/tree/jep/jep based on the official JEP template and will further work tomorrow to have a first discussion basis.

In the meantime, feel free to scan the current state to see if we think in the same direction.

**Comment by echarles** [comment]
For now this inception JEP just focusses on landscape review and invitation for to the jupyter ecosystem to use the work being currently done in `https://github.com/jupyterlab-contrib/jupyter-ui-toolkit`.

To make it more clear, it may be wise to propose the migration to a top level repo hosted in e.g. `https://github.com/jupyter/ui-components`.

`jupyter` org because it aims any jupyter related ui, `ui-components` because it deliver react.js components, web components... to build user interfaces.

WDYT @fcollonval @ellisonbg @jasongrout

**Comment by echarles** [comment]
@afshin

**Comment by echarles** [comment]
The npm packages are for now published under `@jupyter-notebook`, and https://github.com/jupyter-notebook having reserved a a GitHub org (I think I have read that some time ago), we could also discuss about the package name.

The proposal clearly mentions that the widgets should be spread for all kind of jupyter use cases, going beyond the notebook, `@jupyter-notebook` may be revisited. Ideally to the npm org `@jupyter`

**Comment by echarles** [comment]
@krassowski may also be interested in this.

**Comment by fcollonval** [comment]
One note about the naming on npm package. The _jupyter_ organization is hold by someone already. I reached out to npmjs.org 5 months ago about options to transfer ownership of it. But I didn't get any answer.
The _jupyter-notebook_ has been taken by @jtpio due to that. But definitely naming is not final.

**Comment by jtpio** [comment]
> The npm packages are for now published under `@jupyter-notebook`, and https://github.com/jupyter-notebook having reserved a a GitHub org (I think I have read that some time ago), we could also discuss about the package name.

Linking to the following two issues for more context:

- https://github.com/jupyterlab/retrolab/issues/313
- https://github.com/jupyter/notebook-team-compass/issues/2

**Comment by echarles** [comment]
Yes, I had read about that some time ago but didn't know the status of npmjs.org reply.

Package naming and repository location would be the final decision and we have to polish and brainstorm on this initial JEP content. Still good to propose in the proposal a generic GitHub and Npm name.

**Comment by echarles** [comment]
@fcollonval @jtpio I think we have now a good basis to start the JEP `pre-proposal` process documented on https://jupyter.org/enhancement-proposals/jupyter-enhancement-proposal-guidelines/jupyter-enhancement-proposal-guidelines.html#jep-submission-workflow. Thx again for your inputs on work on this.  I propose to shepherd the JEP and assign you in the review team. WDYT?

**Comment by fcollonval** [comment]
Thanks @echarles to pushing on this.

Let's start the pre-proposal process

**Comment by echarles** [comment]
Pre proposal opened on https://github.com/jupyter/enhancement-proposals/issues/88

**Comment by echarles** [comment]
Closing as a PR is now available for review in the official jupyter enhancement-proposals https://github.com/jupyter/enhancement-proposals/pull/89.

Thx all for you contributions.
